seuratBootstrap <-
function(group=c("sudo","docker"), scratch.folderDOCKER, scratch.folderHOST, file, nPerm, permAtTime, percent, separator, logTen=0, pcaDimensions, seed=111,sparse=FALSE,format="NULL",resolution=0.6){

  isDocker <- is_running_in_docker()

      if (isDocker == TRUE){
      scratch.folderHOST <- gsub("\\\\", "/", scratch.folderHOST)
      }

      if(isDocker == FALSE){
    scratch.folderDOCKER=scratch.folderHOST
    }

  if(!sparse){
    seuratPermutation(group=group, scratch.folderDOCKER=scratch.folderDOCKER, scratch.folderHOST=scratch.folderHOST, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed,resolution=resolution)
    cluster.path <- paste(data.folder=dirname(file), "Results", strsplit(basename(file),"\\.")[[1]][1], sep="/")
    cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  if(length(cluster)==1){
    permAnalysisSeurat(group=group, scratch.folderDOCKER=scratch.folderDOCKER, scratch.folderHOST=scratch.folderHOST, file=file, nCluster=cluster, separator=separator, sp=0.8)
  } else{
    cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
    cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
    exitStatus <- 5
    writeLines(as.character(exitStatus), "ExitStatusFile")
    return(5)
  }

  }else{

    seuratPermutation(group=group, scratch.folderDOCKER=scratch.folderDOCKER, scratch.folderHOST=scratch.folderHOST, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed,sparse,format=format,resolution=resolution)
   matrixName=strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])]
   data.folder=paste(strsplit(dirname(file),"/")[[1]][-length(strsplit(dirname(file),"/")[[1]])],collapse="/")
   cluster.path <- paste(data.folder=data.folder, "Results",strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])], sep="/")



    cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  if(length(cluster)==1){
    permAnalysisSeurat(group=group, scratch.folderDOCKER=scratch.folderDOCKER, scratch.folderHOST=scratch.folderHOST, file=file, nCluster=cluster, separator=separator, sp=0.8,sparse=sparse,format=format)
  } else{
    cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
    cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
    exitStatus <- 5
    writeLines(as.character(exitStatus), "ExitStatusFile")
    return(5)
  }







  }

}
